name: Build Frontend

on:
  pull_request:
    types:
      - closed
    branches:
      - Staging

jobs:
  merged:
    name: Check if PR is merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

  build_frontend:
    name: Build Frontend Artifact
    needs: merged
    runs-on: ${{matrix}}
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup CI frontend
        working-directory: ./frontend
        run: npm ci
      - name: Run build frontend
        working-directory: ./frontend
        run: npm run build --if-present