name: Code Quality

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - Updating-Code-Standards
  pull_request:
    branches:
      - Updating-Code-Standards

jobs:
  run-linters:
    name: Fix Linting and Formatting Issues
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies frontend
        working-directory: ./frontend
        run: npm ci

      - name: Install Node.js dependencies backend
        working-directory: ./backend
        run: npm ci

      - name: Automatically Fix Linting Issues Frontend
        working-directory: ./frontend
        continue-on-error: true
        run: npm run lint:fix

      - name: Automatically Fix Styling Issues Frontend
        working-directory: ./frontend
        continue-on-error: true
        run: npm run styles:fix

      - name: Automatically Fix Linting Issues Backend
        working-directory: ./backend
        continue-on-error: true
        run: npm run lint:fix

      - name: Automatically Fix Styling Issues Backend
        working-directory: ./backend
        continue-on-error: true
        run: npm run styles:fix

  check-linters:
    name: Check for Linting and Formatting Issues
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Node.js dependencies frontend
        working-directory: ./frontend
        run: npm ci

      - name: Install Node.js dependencies backend
        working-directory: ./backend
        run: npm ci

      - name: Check for Linting Issues Frontend
        working-directory: ./frontend
        continue-on-error: true
        run: npm run lint:check

      - name: Check for Styles Issues Frontend
        working-directory: ./frontend
        continue-on-error: true
        run: npm run styles:check

      - name: Check for Linting Issues Backend
        working-directory: ./backend
        continue-on-error: true
        run: npm run lint:check

      - name: Check for Styles Issues Backend
        working-directory: ./backend
        continue-on-error: true
        run: npm run styles:check