name: Code Quality

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - Updating-Code-Standards
  pull_request:
    branches:
      - Updating-Code-Standards

jobs:
  run-linters:
    name: Run linters and formatters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies frontend
        working-directory: ./frontend
        run: npm ci

      - name: Install Node.js dependencies backend
        working-directory: ./backend
        run: npm ci

      - name: Automatically Fix Code Quality Issues Frontend
        working-directory: ./frontend
        run: npm run quality:fix-all

      - name: Check Code Quality Issues Frontend
        working-directory: ./frontend
        run: npm run quality:check-all

      - name: Automatically Fix Code Quality Issues Backend
        working-directory: ./backend
        run: npm run quality:fix-all

      - name: Check Code Quality Issues Backend
        working-directory: ./backend
        run: npm run quality:check-all